name: Update Activity Card Hourly

on:
  schedule:
    - cron: "45 */6 * * *"
  workflow_dispatch:

jobs:
  generate-activity-card:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      GH_USERNAME: "${{ secrets.GH_USERNAME }}"
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install --upgrade uv

      - name: Install project dependencies
        run: uv sync

      - name: Generate activity card
        run: uv run python -m src.github_activity_card

      - name: Get current date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Configure git user
        run: |
          git config user.name "cards-bot"
          git config user.email "cards-bot@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add ./cards/github_activity_card_dark.svg ./cards/github_activity_card_light.svg
          git commit -m "Update activity card ($DATE)" || echo "Nothing to commit"
          git push
