name: Update Cards Daily

on:
  schedule:
    - cron: "45 6 * * *"
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log verbosity level"
        required: false
        default: "INFO"
        type: choice
        options:
          - INFO
          - DEBUG
          - NONE

jobs:
  generate-cards:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      GH_USERNAME: "${{ secrets.GH_USERNAME }}"
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
      LOG_LEVEL: "${{ inputs.log_level || 'INFO' }}"

    steps:
      - uses: actions/checkout@v7

      - name: Extract Python version
        id: python-version
        run: echo "version=$(make get_python_required_version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - uses: astral-sh/setup-uv@v7

      - name: Install project dependencies
        run: make sync

      - name: Generate cards
        run: make github_cards

      - name: Get current date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Configure git user
        run: |
          git config user.name "cards-bot"
          git config user.email "cards-bot@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add ./cards/*
          git commit -m "Generated new cards ($DATE)" || echo "Nothing to commit"
          git push
